name: Test & Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install
      run: pnpm install
    
    - name: Test
      run: pnpm test

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        BUILD_ID: ${{ github.sha }}
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: >
        vercel
        --prod
        --build-env BUILD_ID=${BUILD_ID}
        --yes
        --env NODE_ENV=production
        --public
        --token=${ZEIT_TOKEN}

    - name: Verify
      uses: wei/curl@master
      with:
        args: https://www.gxdrecords.com
