name: Test & Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    
    - name: Install
      run: yarn install
    
    - name: Test
      run: yarn test

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        BUILD_ID: ${{ github.sha }}
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: >
        now
        --prod
        --build-env BUILD_ID=${BUILD_ID}
        --confirm
        --env NODE_ENV=production
        --public
        --no-clipboard
        --token=${ZEIT_TOKEN}

    - name: Verify
      uses: wei/curl@master
      with:
        args: https://www.gxdrecords.com
